import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import { UserContextProvider } from "./Context/usercontext";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <UserContextProvider>

   
      <main>

      {children}
      </main>
      </UserContextProvider>
      </body>
    </html>
  );
}
